spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ibatis1?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath*:com/pop/ibatis/shardingibatis/mapper/*Mapper.xml"
  type-aliases-package: com.pop.ibatis.shardingibatis.entity
